name: mentor
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mamba
  - numpy
  - pandas
  - pip
  - python
  - r-base=4.1
  - r-tidyverse
  - r-cowplot
  - r-dendextend
  - r-rcolorbrewer
  - r-optparse
  - r-ggnewscale
  - r-latex2exp
  - r-igraph
  - r-biocmanager
  - r-data.table
  - r-doparallel
  - r-foreach
  - r-patchwork
  - r-iterators
  - r-dplyr
  - r-stringr
  - r-matrix
  - r-irkernel
  - bioconductor-randomwalkrestartmh
  - scikit-learn>=1.4
  - scipy
  - pytest
  - pip:
    - dynamicTreeCut
