name: functional-partitioning
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mamba
  - matplotlib
  - numpy
  - pandas
  - pip
  - python
  - scikit-learn>=1.2
  - scipy
  - seaborn
  - pytest
  - pip:
    - dynamicTreeCut
