name: functional-partitioning
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ipykernel
  - mamba
  - matplotlib
  - numpy
  - pandas
  - pip
  - python
  - scikit-learn
  - scipy
  - seaborn
